services:
  myapp:
    image: yourusername/myapp:latest  # Pulls the image from Docker Hub
    container_name: myapp  # Optional, to set a custom container name
    ports:
      - "8080:8080"  # Maps host port 8080 to container port 8080
    restart: always  # Optional, to automatically restart if it stops
