name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image for ARM64
        run: |
          docker buildx build --platform linux/arm64 -t bikram82/myapp:latest .

      # Step 3: Log in to Docker Hub (or another registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Push Docker image to Docker Hub
        run: |
          docker push bikram82/myapp:latest
deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Pull the Docker image (ARM64) from Docker Hub
    - name: Pull Docker image from Docker Hub
      run: |
        docker pull bikram82/myapp:latest

    # Step 3: Deploy the Docker container locally (optional)
    - name: Run Docker container locally
      run: |
        docker run -d -p 8080:8080 --name myapp bikram82/myapp:latest