name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Adjust branch as needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or another registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # Optional: Deploy to Docker container on host or cloud
      - name: Deploy Docker container
        run: |
          docker-compose pull bikram82/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker-compose up -d --remove-orphans -p 8080:8080 --name myapp ${{ secrets.DOCKER_USERNAME }}/myapp:latest
